# Generated by Django 2.2.7 on 2019-12-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='age',
            field=models.CharField(choices=[('juvenile', 'juvenile'), ('adult', 'adult')], help_text='Age', max_length=16),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='latitude',
            field=models.DecimalField(decimal_places=13, help_text='Latitude', max_digits=15),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='location',
            field=models.CharField(choices=[('above ground', 'above ground'), ('ground plane', 'ground plane')], help_text='Location', max_length=16),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='longitude',
            field=models.DecimalField(decimal_places=13, help_text='Longitude', max_digits=15),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='primary_fur_color',
            field=models.CharField(choices=[('gray', 'gray'), ('cinnamon', 'cinnamon'), ('black', 'black')], help_text='Primary Fur Color', max_length=16),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='shift',
            field=models.CharField(choices=[('am', 'am'), ('pm', 'pm')], help_text='Shift', max_length=16),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='unique_squirrel_id',
            field=models.CharField(help_text='ID', max_length=255),
        ),
    ]
